mangara/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mangara.views.home', name='home'),
    # url(r'^mangara/', include('mangara.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('rememberthelist.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}, name='media')
)

rememberthelist/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',


    url(r'^(?P<list_key>[a-zA-Z0-9]{62})$', views.show_list, name='show_list'),
   # url(r'^new_list$', views.new_list, name='new_list'),
    url(r'^new_item/(?P<list_key>[a-zA-Z0-9]{62})$', views.new_item, name='new_item'),
    url(r'^delete_item$', views.delete_item, name='delete_item') ,
    url(r'^update_item_pos$', views.update_item_pos, name='update_item_pos') ,
    url(r'^check_item$', views.check_item, name='check_item') ,
    url(r'^update_text_item$', views.update_text_item, name='update_text_item') ,
    url(r'^$', views.lists, name='home'),
    #url(r'^', views.lists , name='homes'),
)

rememberthelist/models.py
from django.db.models import Model, SlugField, CharField, DateTimeField, BooleanField, PositiveIntegerField, ForeignKey, permalink, FloatField


class List(Model):
    key = SlugField(max_length=62, unique=True)   # All list keys are 62 chars long
    name = CharField(max_length=140, blank=False)
    creation_date = DateTimeField(auto_now=True)
    last_modification_date = DateTimeField(auto_now=True)


    def __unicode__(self):
        return self.name


    @permalink
    def get_absolute_url(self):
        return ('show_list', None, {'list_key': self.key})

    # def get_absolute_url(self):
    #     return "/%s" % self.key


class Item(Model):
    text = CharField(max_length=140, blank=False)
    checked = BooleanField(default=False)
    position = FloatField(blank=True)
    lst = ForeignKey(List)



    #nextpost =  model.objects.order_by('-position')[0].position + 1
    #self.objects.filter(lst=una).order_by('-position')[0].position
    # model = self.__class__

    def save(self, *args, **kwargs):

        if ( self.position == None ):
            lst = self.lst
            items = Item.objects.filter(lst=lst).order_by('-position')
            if ( len(items) == 0 ):
                self.position = 1
            else:
                self.position = items[0].position + 1

        return super(Item, self).save(*args, **kwargs)


    def __unicode__(self):
        return self.text

    # class Meta:
    #     order_with_respect_to = 'list'
    #     #ordering = ['number']
    #     #unique_together = ('list', 'number')

rememberthelist/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import List, Item

class ListForm(forms.ModelForm):
    name = forms.CharField(
        label='',
    )
    class Meta:
        model = List
        fields = ('key', 'name',)
        widgets = {'key': forms.HiddenInput()}

class ItemForm(forms.ModelForm):
    text = forms.CharField(
        label='New Item',
        widget=forms.TextInput(),
    )

    class Meta:
        model = Item
        fields = ('text','lst')
        widgets = {'lst': forms.HiddenInput(), 'position':forms.HiddenInput()}


class EditItemForm(forms.ModelForm):
    text = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class': "item-text hidden-text"}),
    )
    checked = forms.BooleanField(
        label='',
        widget=forms.CheckboxInput(attrs={'class': "item-checked"}),
    )


    class Meta:
        model = Item
        fields = ('id', 'text', 'lst', 'checked','position')
        widgets = {'lst': forms.HiddenInput(), 'position':forms.HiddenInput()}

rememberthelist/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import List, Item
from .forms import ListForm, ItemForm, EditItemForm
from .auxiliar import *
import json
import string
from random import choice

LIST_KEY_CHARS = string.ascii_letters + string.digits
#ist_key = "".join([choice(LIST_KEY_CHARS) for x in range(62)])

# def if_list_fun(_id, key, function):
#     lst = List.objects.get(id=_id)
#     if ( lst.key == key ):
#         function()



# def new_list(request):
#     if request.method == 'POST':
#         return HttpResponse(json.dumps({'message': "hola soy post"}))
#     return HttpResponse(json.dumps({'message': "hola soy get"  }))



def lists(request):
    key = "".join([choice(LIST_KEY_CHARS) for x in range(62)])
    form = ListForm(initial={'key':key, })

    if request.method == 'POST':
        form = ListForm(request.POST)

        if form.is_valid():
            lst = form.save()
            return HttpResponseRedirect(reverse('show_list',  kwargs={'list_key': lst.key}))

    lists = List.objects.all()
    return render(request, 'lists.html', {'lists': lists, 'form':form})

def new_item(request, list_key):
    if request.method == 'POST':
        lst = List.objects.get(id=request.POST.get('lst'))
        if ( lst.key == list_key ):
            form = ItemForm(request.POST)
            #return HttpResponse(json.dumps({'message': "hola post", "post": request.POST}))
            if form.is_valid():
                item = form.save()
                ritemForm = EditItemForm(initial={'lst':lst, })

                return HttpResponse(json.dumps({'message': 'ok',
                                                'id':item.id,
                                                'text':item.text,
                                                'position': item.position,
                                            }))
    return redirect('home')

def delete_item(request):
    if request.method == 'POST':
        key = request.POST.get('list_key')
        lst = List.objects.get(id=request.POST.get('list_id'))

        if ( lst.key == key ):
            item_id = request.POST.get('item_id')
            item = Item.objects.get(id=item_id)
            item.delete()
            return HttpResponse(json.dumps({'message': "hola soy post de delete"  }))
    return redirect('home')

def update_item_pos(request):
    if request.method == 'POST':
        key = request.POST.get('list_key')
        lst = List.objects.get(id=request.POST.get('list_id'))
        pos = request.POST.get('item_pos')

        #TODO validate number
        if ( lst.key == key ):
            item_id = request.POST.get('item_id')
            item = Item.objects.get(id=item_id)
            item.position = pos
            item.save()
            #item.update(position=pos)
            return HttpResponse(json.dumps({'message': "hola soy post de update" +   pos + item_id  }))

    return redirect('home')


def check_item(request):
    if request.method == 'POST':
        key = request.POST.get('list_key')
        lst = List.objects.get(id=request.POST.get('list_id'))

        # #TODO validate number
        if ( lst.key == key ):
            item_id = request.POST.get('item_id')
            item = Item.objects.get(id=item_id)
            item.checked = not item.checked
            item.save()

            return HttpResponse(json.dumps({'message': "hola soy post de check"   }))

    return redirect('home')


def update_text_item(request):
    if request.method == 'POST':
        key = request.POST.get('list_key')
        lst = List.objects.get(id=request.POST.get('list_id'))

        if ( lst.key == key ):
             item_id = request.POST.get('item_id')
             item = Item.objects.get(id=item_id)
             item.text = request.POST.get('item_text')
             item.save()
             return HttpResponse(json.dumps({'message': "hola soy update item"  }))

    return redirect('home')



def show_list(request, list_key):

    #return redirect('home')
    try:
        lst = List.objects.get(key=list_key)
    except:
        return redirect('home')

    form = ItemForm(initial={'lst':lst, })
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()

    items = Item.objects.filter(lst=lst).order_by('position')

    def makeItemForm(item):
        return  EditItemForm(instance=item)

    itemForms = list(map(makeItemForm, items))

    return render(request, 'list.html', {
        'list':lst,
        'form' : form,
        'itemForms': itemForms,
        'tmp' : list_key,
    })

rememberthelist/templates/list.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>Remember the list</title>
    <link href="{{MEDIA_URL}}/css/style.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="bodylist">

    <div id="header">
      <h2>{{ list.name }}</h2>
    </div>

    <div id="main">

      <div id="url">
        This list&#39;s URL is<br/>
        <a href="/{{ tmp }}">http://tacuco.com/{{ tmp }} </a><br/>
        Copy it somewhere so you can remember it.
      </div>


      <div id="additem">
        <form id="form" method="POST">{% csrf_token %}
           {{ form }}
           <button type="submit" class="save btn btn-default">Create</button>
        </form>
      </div>


    <ol id="itemForms">
        {% for itemForm in itemForms %}

        <li id="itemForm{{ itemForm.initial.id }}"
            class="itemForm"
            data-itemID="{{ itemForm.initial.id }}" >

          <form method="POST">{% csrf_token %}
            <table>
              <tr>
                <td><img class='item-move' src='{{MEDIA_URL}}/images/move.png' /></td>
                <td><img class="item-delete" src="{{MEDIA_URL}}/images/delete.png" /></td>
                <td> {{ itemForm.checked }} </td>
                <td>
                  <span class='item-plane-text'> {{ itemForm.text.value }} </span>
                  {{ itemForm.text }}
                </td>
                <td>  <button class="item-save" type="submit">Save</button> </td>
              </tr>
            </table>

            {{ itemForm.position }}
            {{ itemForm.lst }}

          </form>
        </li>

        {% endfor %}
      </ol>




      <div id="clone" style="display:none">

        <li id='' class='itemForm ui-sortable-handle' data-itemid=''>
          <form method='POST'>{% csrf_token %}
            <table>
              <tr>
                <td><img class='item-move' src='{{MEDIA_URL}}/images/move.png' /></td>
                <td><img class='item-delete' src='{{MEDIA_URL}}/images/delete.png' /></td>
                <td><input id="id_checked" class="item-checked" name="checked" type="checkbox"> </td>
                <td>
                  <span class="item-plane-text"> </span>
                  <textarea id="id_text" rows="10" cols="40" name="text" class="item-text hidden-text"></textarea>
                </td>
                <td><button style="display: none;" class="item-save" type="submit">Save</button> </td>
              </tr>
            </table>

            <input name="position" value="" id="id_position" type="hidden" />
            <input name="lst" value="{{list.id}}" id="id_lst" type="hidden" />

          </form>

        </li>
      </div>

    </div>

<script type="text/javascript" src="{{MEDIA_URL}}/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}/js/jquery-ui-1.11.2.custom/jquery-ui.min.js"></script>


<script>
$(document).ready(function() {

    $('input:checked').siblings('#id_text').addClass('cheked');

 //   $('.item-text').prop('disabled', true);
    //$('.item-text').attr('style', 'border:0; width:300px; background:white;');
    $('.item-save').hide();


    function make_item(item_id, position, text){
        new_item = $('#clone').find('li').clone();

        new_item.attr('id', 'itemForm'+item_id);
        new_item.attr('data-itemid', item_id);
        new_item.find('#id_text').text(text);
        new_item.find('#id_position').val(position);
        new_item.find('.item-plane-text').text(text);

        $('#itemForms').append(new_item);
    }


    $('#form').submit(function(e){
        e.preventDefault();
        $.post( "{% url new_item list_key=list.key %}",$(this).serialize(), function(data) {
            //console.log(data)
            item = jQuery.parseJSON(data)
            //console.log(item.id)
            $('#form').trigger("reset");
            make_item(item.id, item.position, item.text)

        }) .fail(function() {
            alert( "error" );
        })
    });


    function delete_item(item_id){
        $.post(  "{% url delete_item %}",{
            csrfmiddlewaretoken: '{{csrf_token}}',
            item_id: item_id,
            list_key: '{{list.key}}',
            list_id: '{{list.id}}',
        }).done(function( data ) {
            $('#itemForm'+item_id).remove();
            //console.log( "Data Loaded: " + data + item_id);
        }).fail(function() {
            console.log( "error" );
        });
    }

    function check_item(item_id){

        $.post(  "{% url check_item %}",{
            csrfmiddlewaretoken: '{{csrf_token}}',
            item_id: item_id,
            list_key: '{{list.key}}',
            list_id: '{{list.id}}'
        }).done(function( data ) {
            console.log( "Data Loaded: " + data );
        }).fail(function() {
            console.log( "error" );
        });

    }

    function edit_item(item_id, text){
        //console.log( item_id + " " + text );

        $.post(  "{% url update_text_item %}",{
            csrfmiddlewaretoken: '{{csrf_token}}',
            item_id: item_id,
            list_key: '{{list.key}}',
            list_id: '{{list.id}}',
            item_text : text,
        }).done(function( data ) {
            console.log( "Data Loaded: " + data );
        }).fail(function() {
            console.log( "error" );
        });

    }


   $('#itemForms').sortable({

        stop: function(event, ui) {

            var inf = Number(ui.item.prev().find('#id_position').val());
            var sup = Number(ui.item.next().find('#id_position').val());
            var pos;


            if (!inf) inf = 0;
            if (!sup) pos = Math.ceil(inf) + 1
            if (!pos) pos = inf + ((sup - inf) / 2);

            ui.item.data('pos', pos);
            item_id = ui.item.data('itemid');

            $.post(  "{% url update_item_pos %}",{
                csrfmiddlewaretoken: '{{csrf_token}}',
                item_id: item_id,
                list_key: '{{list.key}}',
                list_id: '{{list.id}}',
                item_pos: pos
            }).done(function( data ) {
                $(ui.item).find('#id_position').val(pos)

            }).fail(function() {
                console.log( "error" );
            });

        },
    });

    $('#itemForms').on('click','.item-save', function(event) {
        event.preventDefault();
        item_id = $(this).parents('.itemForm').data('itemid');
        text = $('#itemForm'+item_id).find('#id_text').val();
        $('#itemForm'+item_id).find('.item-save').hide();
        edit_item(item_id, text);

        $('#itemForm'+item_id).find('.item-text').addClass('hidden-text')
        $('#itemForm'+item_id).find('.item-plane-text').removeClass('hidden-text');
        $('#itemForm'+item_id).find('.item-plane-text').text(text);
        $('#itemForm'+item_id).find('#id_text').removeClass('please_save');
        $('#itemForm'+item_id).removeClass('item-select');
        last_item = false;
    });

    $('#itemForms').on('click','.item-delete', function(event) {
        item_id = $(this).parents('.itemForm').data('itemid');
        delete_item( item_id );
    });

    $('#itemForms').on('click','.item-checked', function(event) {
        item_id = $(this).parents('.itemForm').data('itemid');
        if (this.checked)
            $(this).parents('.itemForm').find("#id_text").addClass('cheked');
        else
            $(this).parents('.itemForm').find("#id_text").removeClass('cheked');
        check_item(item_id);
    }); //focus



    // $('#itemForms').on('focus','.item-text', function(event) {
    //     item_id = $(this).parents('.itemForm').data('itemid');
    //     $('.item-save').hide();
    //     $('#itemForm'+item_id).find('.item-save').show();
    // });
    // $('#itemForms').on('change','.item-text', function(event) {
    //     item_id = $(this).parents('.itemForm').data('itemid');
    //      $('#itemForm'+last_item).find('.item-plane-text').addClass('please_save');
    // });


    last_item = false

    $('#itemForms').on('click','.item-plane-text', function(event) {

        item_id = $(this).parents('.itemForm').data('itemid');
        $('#itemForm'+item_id).addClass('item-select');
        text_plane = $(this);
        text_input =  $('#itemForm'+item_id).find('.item-text');
        $('.item-save').hide();

        if (last_item){
            $('#itemForm'+last_item).find('.item-text').addClass('hidden-text')
            $('#itemForm'+last_item).find('.item-plane-text').removeClass('hidden-text');
            $('#itemForm'+last_item).removeClass('item-select');
        }

        $(this).addClass('hidden-text');
        last_item  = item_id;
        $('#itemForm'+item_id).find('.item-text').removeClass('hidden-text');

        $('#itemForm'+item_id).find('.item-save').show();
        //        $('#itemForm'+item_id).find('.item-text').focus();
        text_area = $('#itemForm'+item_id).find('.item-text')
        text_area_val = text_area.val();
        //console.log(text_area_val);
        text_area.focus().val('');
        text_area.val( text_area_val );


    });
    // $('.itemForm').on('click', function(event) {

    //     var target = $( event.target );
    //     var target_class = target.attr('class');
    //     item_id = $(this).data('itemid');

    //     switch (target_class){
    //     case 'item-text':
    //         console.log(target_class);
    //         break;
    //     case 'item-checked':
    //         check_item(item_id)
    //         break;
    //     case 'item-delete':
    //         delete_item(item_id)
    //         break;
    //     case 'item-edit':
    //         console.log(target_class);
    //         break;
    //     case 'item-button':
    //         event.preventDefault();
    //         edit_item(item_id,$(this).find('#id_text').val());
    //         break;
    //     }

    // });



});

</script>




  </body>
</html>

rememberthelist/templates/lists.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
  <head>
    <title>Remember the list</title>
    <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}/css/style.css" />
  </head>

  <body class="index">

    <div id="header"></div>

    <div id="main">
      <form id="form" action="" method="post">{% csrf_token %}
        <p>Write a name for your list: </p>
        {{ form }}
        <input type="submit" value="Create list" />
      </form>
    </div>


    <div id="footer">
      Copyright &#169;  mnagara.net 2014
    </div>

  </body>
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//mangara.net/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 4]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//mangara.net/piwik/piwik.php?idsite=4" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
</html>